# ملف إعدادات Netlify (نسخة مُصحّحة)

[build]
  publish = "/"
  functions = "netlify/functions"

# ===================================================================
# الترتيب هنا في غاية الأهمية. Netlify يقرأ القواعد من الأعلى للأسفل.
# ===================================================================

# ✅ القاعدة الجديدة: لجعل رابط /admin يعرض صفحة admin.html
# يجب أن تأتي هذه القاعدة "قبل" قاعدة /admin/* العامة
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# قاعدة توجيه طلبات API الخاصة بالمسؤولين إلى الوظيفة السحابية
[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/api/admin/:splat"
  status = 200
  force = true

# قاعدة توجيه طلبات API العامة إلى الوظيفة السحابية
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
