# ملف إعدادات Netlify

# إعدادات البناء الأساسية
[build]
  # المجلد الذي يحتوي على ملفات الموقع النهائية (HTML, CSS, JS)
  publish = "/"
  # المجلد الذي يحتوي على الوظائف السحابية
  functions = "netlify/functions"

# إعادة توجيه الطلبات التي تبدأ بـ /api/ أو /admin/ إلى الوظيفة السحابية
# هذه القواعد ضرورية لإنشاء واجهة برمجية (API) نظيفة.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true # ضروري لطلبات POST, PUT, DELETE

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/api/admin/:splat" # توجيه أدق لمسارات المسؤول
  status = 200
  force = true
